export const tekster = {
  no: {
    // Login
    tagline: 'Digitalt matkort for sykehjem',
    epost: 'Epostadresse',
    passord: 'Passord',
    loggInn: 'Logg inn',
    kontoLåst: 'Kontoen er låst',
    glemmtPassord: 'Glemt passord?',
    feilEpostPassord: 'Feil epost eller passord – prøv igjen',
    serverFeil: 'Kunne ikke kontakte serveren. Sjekk at API-et kjører og prøv igjen.',
    fyllInn: 'Fyll inn epost og passord.',
    kontoLåstMelding: 'Kontoen er låst etter 5 forsøk. Prøv igjen om 15 minutter.',

    // Avdelingsvalg
    godMorgen: 'God morgen',
    godDag: 'God dag',
    godKveld: 'God kveld',
    hvilkenAvdeling: 'Hvilken avdeling jobber du på i dag?',
    loggUt: 'Logg ut',

    // Pasientliste
    pasienter: 'Pasienter',
    søkPåNavn: 'Søk på navn...',
    alle: 'Alle',
    allergi: 'Allergi',
    fortykning: 'Fortykning',
    aktivePasienter: 'aktive pasienter',

    // Pasientkort
    pasientkort: 'Pasientkort',
    matprofil: 'Matprofil',
    foreslåEndring: 'Foreslå endring',
    sendForslag: 'Send forslag ✓',
    avbryt: 'Avbryt',
    forslagSendt: 'Forslag sendt til godkjenning',
    langtidsplass: 'Langtidsplass',
    korttidsplass: 'Korttidsplass',

    // Godkjenning
    tilGodkjenning: 'Til godkjenning',
    eldsteForst: 'forslag venter – eldste først',
    ingenForslag: '🎉 Ingen forslag venter på godkjenning!',
    godkjenn: 'Godkjenn',
    avvis: 'Avvis',
    sendtAv: 'Sendt av',
    gammel: 'Gammel',
    ny: 'Ny',
    original: 'Original:',
    oversattTilNorsk: 'Oversatt til norsk:',
    automatiskOversattAdvarsel: '⚠️ Automatisk oversatt – sjekk at betydningen stemmer',
    endringGodkjent: '✓ Endring godkjent og oppdatert!',
    forslagAvvist: 'Forslag avvist.',
    skrivBegrunnelse: 'Skriv begrunnelse for avvisning...',
    sendAvvisning: 'Send avvisning',
    varsler: 'Varsler',
    rom: 'Rom',
    allergier: 'Allergier',
    fortykningsbehov: 'Fortykningsbehov',
    kaffeTe: 'Kaffe/Te',
    drikke: 'Drikke',
    frokost: 'Frokost',
    kveldsmat: 'Kveldsmat',
    konsistensMat: 'Konsistens mat',
    hvorSpiser: 'Hvor spiser',
    redskap: 'Redskap',
    likerIkke: 'Liker ikke',
    sistEndret: 'Sist endret',
    dia: 'DIA',
    laster: 'Laster...',
    oversetterInnhold: 'Oversetter innhold...',
    sender: 'Sender...',
    tilbake: 'Tilbake',
    ingenPasientValgt: 'Ingen pasient valgt.',
    ingenProfilData: 'Ingen profildata funnet for denne pasienten.',
    manglerMatprofil: 'Matprofil mangler for denne pasienten.',
    kunneIkkeHenteProfil: 'Kunne ikke hente profildata. Sjekk at API-et kjører.',
    kunneIkkeOversette: 'Kunne ikke oversette innhold. Sjekk at Azure Translator er konfigurert på API-et.',
    kunneIkkeSendeForslag: 'Kunne ikke sende forslag. Prøv igjen.',
    kunneIkkeHenteForslag: 'Kunne ikke hente ventende forslag.',
    kunneIkkeGodkjenne: 'Kunne ikke godkjenne forslaget.',
    kunneIkkeAvvise: 'Kunne ikke avvise forslaget.',
  },

  en: {
    // Login
    tagline: 'Digital food card for nursing homes',
    epost: 'Email address',
    passord: 'Password',
    loggInn: 'Log in',
    kontoLåst: 'Account locked',
    glemmtPassord: 'Forgot password?',
    feilEpostPassord: 'Wrong email or password – try again',
    serverFeil: 'Could not reach the server. Check that the API is running and try again.',
    fyllInn: 'Please enter email and password.',
    kontoLåstMelding: 'Account locked after 5 attempts. Try again in 15 minutes.',

    // Avdelingsvalg
    godMorgen: 'Good morning',
    godDag: 'Good afternoon',
    godKveld: 'Good evening',
    hvilkenAvdeling: 'Which department are you working in today?',
    loggUt: 'Log out',

    // Pasientliste
    pasienter: 'Patients',
    søkPåNavn: 'Search by name...',
    alle: 'All',
    allergi: 'Allergy',
    fortykning: 'Thickening',
    aktivePasienter: 'active patients',

    // Pasientkort
    pasientkort: 'Patient card',
    matprofil: 'Food profile',
    foreslåEndring: 'Suggest change',
    sendForslag: 'Send suggestion ✓',
    avbryt: 'Cancel',
    forslagSendt: 'Suggestion sent for approval',
    langtidsplass: 'Long-term stay',
    korttidsplass: 'Short-term stay',

    // Godkjenning
    tilGodkjenning: 'Pending approval',
    eldsteForst: 'suggestions waiting – oldest first',
    ingenForslag: '🎉 No suggestions waiting for approval!',
    godkjenn: 'Approve',
    avvis: 'Reject',
    sendtAv: 'Sent by',
    gammel: 'Old',
    ny: 'New',
    original: 'Original:',
    oversattTilNorsk: 'Translated to Norwegian:',
    automatiskOversattAdvarsel: '⚠️ Automatically translated – verify the meaning',
    endringGodkjent: '✓ Change approved and updated!',
    forslagAvvist: 'Suggestion rejected.',
    skrivBegrunnelse: 'Write reason for rejection...',
    sendAvvisning: 'Send rejection',
    varsler: 'Notifications',
    rom: 'Room',
    allergier: 'Allergies',
    fortykningsbehov: 'Thickening needs',
    kaffeTe: 'Coffee/Tea',
    drikke: 'Drinks',
    frokost: 'Breakfast',
    kveldsmat: 'Evening meal',
    konsistensMat: 'Food consistency',
    hvorSpiser: 'Where eats',
    redskap: 'Utensils',
    likerIkke: 'Dislikes',
    sistEndret: 'Last changed',
    dia: 'DIA',
    laster: 'Loading...',
    oversetterInnhold: 'Translating content...',
    sender: 'Sending...',
    tilbake: 'Back',
    ingenPasientValgt: 'No patient selected.',
    ingenProfilData: 'No profile data found for this patient.',
    manglerMatprofil: 'Food profile missing for this patient.',
    kunneIkkeHenteProfil: 'Could not load profile data. Check that the API is running.',
    kunneIkkeOversette: 'Could not translate content. Check that Azure Translator is configured on the API.',
    kunneIkkeSendeForslag: 'Could not send suggestion. Try again.',
    kunneIkkeHenteForslag: 'Could not load pending suggestions.',
    kunneIkkeGodkjenne: 'Could not approve the suggestion.',
    kunneIkkeAvvise: 'Could not reject the suggestion.',
  },

  es: {
    // Login
    tagline: 'Tarjeta de comida digital para residencias',
    epost: 'Correo electrónico',
    passord: 'Contraseña',
    loggInn: 'Iniciar sesión',
    kontoLåst: 'Cuenta bloqueada',
    glemmtPassord: '¿Olvidaste tu contraseña?',
    feilEpostPassord: 'Email o contraseña incorrectos – inténtalo de nuevo',
    serverFeil: 'No se pudo contactar con el servidor. Comprueba que la API esté en ejecución.',
    fyllInn: 'Por favor ingresa email y contraseña.',
    kontoLåstMelding: 'Cuenta bloqueada tras 5 intentos. Inténtalo en 15 minutos.',

    // Avdelingsvalg
    godMorgen: 'Buenos días',
    godDag: 'Buenas tardes',
    godKveld: 'Buenas noches',
    hvilkenAvdeling: '¿En qué departamento trabajas hoy?',
    loggUt: 'Cerrar sesión',

    // Pasientliste
    pasienter: 'Pacientes',
    søkPåNavn: 'Buscar por nombre...',
    alle: 'Todos',
    allergi: 'Alergia',
    fortykning: 'Espesante',
    aktivePasienter: 'pacientes activos',

    // Pasientkort
    pasientkort: 'Ficha del paciente',
    matprofil: 'Perfil alimentario',
    foreslåEndring: 'Sugerir cambio',
    sendForslag: 'Enviar sugerencia ✓',
    avbryt: 'Cancelar',
    forslagSendt: 'Sugerencia enviada para aprobación',
    langtidsplass: 'Estancia larga',
    korttidsplass: 'Estancia corta',

    // Godkjenning
    tilGodkjenning: 'Pendiente de aprobación',
    eldsteForst: 'sugerencias esperando – más antiguas primero',
    ingenForslag: '🎉 ¡No hay sugerencias pendientes!',
    godkjenn: 'Aprobar',
    avvis: 'Rechazar',
    sendtAv: 'Enviado por',
    gammel: 'Anterior',
    ny: 'Nuevo',
    original: 'Original:',
    oversattTilNorsk: 'Traducido al noruego:',
    automatiskOversattAdvarsel: '⚠️ Traducido automáticamente – comprueba el significado',
    endringGodkjent: '✓ ¡Cambio aprobado y actualizado!',
    forslagAvvist: 'Sugerencia rechazada.',
    skrivBegrunnelse: 'Escribe el motivo del rechazo...',
    sendAvvisning: 'Enviar rechazo',
    varsler: 'Alertas',
    rom: 'Habitación',
    allergier: 'Alergias',
    fortykningsbehov: 'Necesidad de espesante',
    kaffeTe: 'Café/Té',
    drikke: 'Bebidas',
    frokost: 'Desayuno',
    kveldsmat: 'Cena',
    konsistensMat: 'Consistencia de comida',
    hvorSpiser: 'Dónde come',
    redskap: 'Utensilios',
    likerIkke: 'No le gusta',
    sistEndret: 'Último cambio',
    dia: 'DIA',
    laster: 'Cargando...',
    oversetterInnhold: 'Traduciendo contenido...',
    sender: 'Enviando...',
    tilbake: 'Volver',
    ingenPasientValgt: 'Ningún paciente seleccionado.',
    ingenProfilData: 'No se encontraron datos de perfil.',
    manglerMatprofil: 'Falta el perfil de alimentación.',
    kunneIkkeHenteProfil: 'No se pudo cargar el perfil. Comprueba que la API esté activa.',
    kunneIkkeOversette: 'No se pudo traducir el contenido. Comprueba que Azure Translator esté configurado en la API.',
    kunneIkkeSendeForslag: 'No se pudo enviar la sugerencia.',
    kunneIkkeHenteForslag: 'No se pudieron cargar las sugerencias pendientes.',
    kunneIkkeGodkjenne: 'No se pudo aprobar la sugerencia.',
    kunneIkkeAvvise: 'No se pudo rechazar la sugerencia.',
  },

  pl: {
    // Login
    tagline: 'Cyfrowa karta żywieniowa dla domów opieki',
    epost: 'Adres e-mail',
    passord: 'Hasło',
    loggInn: 'Zaloguj się',
    kontoLåst: 'Konto zablokowane',
    glemmtPassord: 'Zapomniałeś hasła?',
    feilEpostPassord: 'Nieprawidłowy e-mail lub hasło – spróbuj ponownie',
    serverFeil: 'Nie można połączyć się z serwerem. Sprawdź, czy API działa.',
    fyllInn: 'Wprowadź e-mail i hasło.',
    kontoLåstMelding: 'Konto zablokowane po 5 próbach. Spróbuj ponownie za 15 minut.',

    // Avdelingsvalg
    godMorgen: 'Dzień dobry',
    godDag: 'Dzień dobry',
    godKveld: 'Dobry wieczór',
    hvilkenAvdeling: 'Na którym oddziale pracujesz dzisiaj?',
    loggUt: 'Wyloguj się',

    // Pasientliste
    pasienter: 'Pacjenci',
    søkPåNavn: 'Szukaj po nazwisku...',
    alle: 'Wszyscy',
    allergi: 'Alergia',
    fortykning: 'Zagęszczenie',
    aktivePasienter: 'aktywnych pacjentów',

    // Pasientkort
    pasientkort: 'Karta pacjenta',
    matprofil: 'Profil żywieniowy',
    foreslåEndring: 'Zaproponuj zmianę',
    sendForslag: 'Wyślij propozycję ✓',
    avbryt: 'Anuluj',
    forslagSendt: 'Propozycja wysłana do zatwierdzenia',
    langtidsplass: 'Pobyt długoterminowy',
    korttidsplass: 'Pobyt krótkoterminowy',

    // Godkjenning
    tilGodkjenning: 'Do zatwierdzenia',
    eldsteForst: 'propozycji oczekuje – najstarsze pierwsze',
    ingenForslag: '🎉 Brak propozycji oczekujących na zatwierdzenie!',
    godkjenn: 'Zatwierdź',
    avvis: 'Odrzuć',
    sendtAv: 'Wysłane przez',
    gammel: 'Stara',
    ny: 'Nowa',
    original: 'Oryginał:',
    oversattTilNorsk: 'Przetłumaczone na norweski:',
    automatiskOversattAdvarsel: '⚠️ Przetłumaczone automatycznie – sprawdź, czy znaczenie się zgadza',
    endringGodkjent: '✓ Zmiana zatwierdzona i zaktualizowana!',
    forslagAvvist: 'Propozycja odrzucona.',
    skrivBegrunnelse: 'Podaj powód odrzucenia...',
    sendAvvisning: 'Wyślij odrzucenie',
    varsler: 'Powiadomienia',
    rom: 'Pokój',
    allergier: 'Alergie',
    fortykningsbehov: 'Zagęszczenie',
    kaffeTe: 'Kawa/Herbata',
    drikke: 'Napoje',
    frokost: 'Śniadanie',
    kveldsmat: 'Kolacja',
    konsistensMat: 'Konsystencja jedzenia',
    hvorSpiser: 'Gdzie je',
    redskap: 'Przybory',
    likerIkke: 'Nie lubi',
    sistEndret: 'Ostatnia zmiana',
    dia: 'DIA',
    laster: 'Ładowanie...',
    oversetterInnhold: 'Tłumaczenie treści...',
    sender: 'Wysyłanie...',
    tilbake: 'Wstecz',
    ingenPasientValgt: 'Nie wybrano pacjenta.',
    ingenProfilData: 'Brak danych profilu.',
    manglerMatprofil: 'Brak profilu żywieniowego.',
    kunneIkkeHenteProfil: 'Nie można załadować profilu. Sprawdź, czy API działa.',
    kunneIkkeOversette: 'Nie można przetłumaczyć treści. Sprawdź, czy Azure Translator jest skonfigurowany w API.',
    kunneIkkeSendeForslag: 'Nie można wysłać propozycji.',
    kunneIkkeHenteForslag: 'Nie można załadować oczekujących propozycji.',
    kunneIkkeGodkjenne: 'Nie można zatwierdzić propozycji.',
    kunneIkkeAvvise: 'Nie można odrzucić propozycji.',
  },

  pt: {
    // Login
    tagline: 'Cartão alimentar digital para casas de repouso',
    epost: 'Endereço de e-mail',
    passord: 'Senha',
    loggInn: 'Entrar',
    kontoLåst: 'Conta bloqueada',
    glemmtPassord: 'Esqueceu a senha?',
    feilEpostPassord: 'E-mail ou senha incorretos – tente novamente',
    serverFeil: 'Não foi possível contactar o servidor. Verifique se a API está em execução.',
    fyllInn: 'Preencha o e-mail e a senha.',
    kontoLåstMelding: 'Conta bloqueada após 5 tentativas. Tente novamente em 15 minutos.',

    // Avdelingsvalg
    godMorgen: 'Bom dia',
    godDag: 'Boa tarde',
    godKveld: 'Boa noite',
    hvilkenAvdeling: 'Em qual setor você trabalha hoje?',
    loggUt: 'Sair',

    // Pasientliste
    pasienter: 'Pacientes',
    søkPåNavn: 'Buscar por nome...',
    alle: 'Todos',
    allergi: 'Alergia',
    fortykning: 'Espessante',
    aktivePasienter: 'pacientes ativos',

    // Pasientkort
    pasientkort: 'Ficha do paciente',
    matprofil: 'Perfil alimentar',
    foreslåEndring: 'Sugerir alteração',
    sendForslag: 'Enviar sugestão ✓',
    avbryt: 'Cancelar',
    forslagSendt: 'Sugestão enviada para aprovação',
    langtidsplass: 'Internação de longo prazo',
    korttidsplass: 'Internação de curto prazo',

    // Godkjenning
    tilGodkjenning: 'Aguardando aprovação',
    eldsteForst: 'sugestões aguardando – mais antigas primeiro',
    ingenForslag: '🎉 Nenhuma sugestão aguardando aprovação!',
    godkjenn: 'Aprovar',
    avvis: 'Recusar',
    sendtAv: 'Enviado por',
    gammel: 'Antiga',
    ny: 'Nova',
    original: 'Original:',
    oversattTilNorsk: 'Traduzido para norueguês:',
    automatiskOversattAdvarsel: '⚠️ Traduzido automaticamente – verifique se o significado está correto',
    endringGodkjent: '✓ Alteração aprovada e atualizada!',
    forslagAvvist: 'Sugestão recusada.',
    skrivBegrunnelse: 'Escreva o motivo da recusa...',
    sendAvvisning: 'Enviar recusa',
    varsler: 'Alertas',
    rom: 'Quarto',
    allergier: 'Alergias',
    fortykningsbehov: 'Necessidade de espessante',
    kaffeTe: 'Café/Chá',
    drikke: 'Bebidas',
    frokost: 'Café da manhã',
    kveldsmat: 'Jantar leve',
    konsistensMat: 'Consistência da comida',
    hvorSpiser: 'Onde come',
    redskap: 'Utensílios',
    likerIkke: 'Não gosta',
    sistEndret: 'Última alteração',
    dia: 'DIA',
    laster: 'Carregando...',
    oversetterInnhold: 'Traduzindo conteúdo...',
    sender: 'Enviando...',
    tilbake: 'Voltar',
    ingenPasientValgt: 'Nenhum paciente selecionado.',
    ingenProfilData: 'Nenhum dado de perfil encontrado.',
    manglerMatprofil: 'Perfil alimentar ausente.',
    kunneIkkeHenteProfil: 'Não foi possível carregar o perfil. Verifique se a API está ativa.',
    kunneIkkeOversette: 'Não foi possível traduzir o conteúdo. Verifique se o Azure Translator está configurado na API.',
    kunneIkkeSendeForslag: 'Não foi possível enviar a sugestão.',
    kunneIkkeHenteForslag: 'Não foi possível carregar sugestões pendentes.',
    kunneIkkeGodkjenne: 'Não foi possível aprovar a sugestão.',
    kunneIkkeAvvise: 'Não foi possível rejeitar a sugestão.',
  },
};
