// <auto-generated />
using System;
using CareCard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareCard.API.Migrations
{
    [DbContext(typeof(CareCardDbContext))]
    [Migration("20260603221211_AddOversattFelt")]
    partial class AddOversattFelt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareCard.API.Models.Ansatt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvdelingId")
                        .HasColumnType("int");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Epost")
                        .IsUnique();

                    b.ToTable("Ansatte");
                });

            modelBuilder.Entity("CareCard.API.Models.EndringsForslag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BehandletAvId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BehandletTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeltNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GammelVerdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NyVerdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NyVerdiOversatt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpprettetAvId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpprettetTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PasientId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PasientId");

                    b.ToTable("EndringsForslag");
                });

            modelBuilder.Entity("CareCard.API.Models.Matprofil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drikke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ErDiabetiker")
                        .HasColumnType("bit");

                    b.Property<string>("Favorittmat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frokost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HarFortykningIDrikke")
                        .HasColumnType("bit");

                    b.Property<string>("HvorSpiser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaffeTe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonsistensDrikke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonsistensMat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kvelds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mellommaltid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merknader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Misliker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasientId")
                        .HasColumnType("int");

                    b.Property<string>("Redskap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SistEndret")
                        .HasColumnType("datetime2");

                    b.Property<int>("SistEndretAvId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PasientId")
                        .IsUnique();

                    b.ToTable("Matprofiler");
                });

            modelBuilder.Entity("CareCard.API.Models.Pasient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvdelingId")
                        .HasColumnType("int");

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fodselsdato")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpprettetTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Romnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pasienter");
                });

            modelBuilder.Entity("CareCard.API.Models.Stellprofil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kommunikasjon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merknader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasientId")
                        .HasColumnType("int");

                    b.Property<string>("Rutiner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SistEndret")
                        .HasColumnType("datetime2");

                    b.Property<int>("SistEndretAvId")
                        .HasColumnType("int");

                    b.Property<string>("StellPreferanser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViktigeHensyn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PasientId")
                        .IsUnique();

                    b.ToTable("Stellprofiler");
                });

            modelBuilder.Entity("CareCard.API.Models.EndringsForslag", b =>
                {
                    b.HasOne("CareCard.API.Models.Pasient", "Pasient")
                        .WithMany()
                        .HasForeignKey("PasientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasient");
                });

            modelBuilder.Entity("CareCard.API.Models.Matprofil", b =>
                {
                    b.HasOne("CareCard.API.Models.Pasient", "Pasient")
                        .WithOne()
                        .HasForeignKey("CareCard.API.Models.Matprofil", "PasientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasient");
                });

            modelBuilder.Entity("CareCard.API.Models.Stellprofil", b =>
                {
                    b.HasOne("CareCard.API.Models.Pasient", "Pasient")
                        .WithOne()
                        .HasForeignKey("CareCard.API.Models.Stellprofil", "PasientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasient");
                });
#pragma warning restore 612, 618
        }
    }
}
